# Generated by Django 6.0.1 on 2026-01-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.IntegerField(max_length=12)),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                ("guests", models.IntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Booking Table",
            },
        ),
    ]
