# Generated by Django 6.0.1 on 2026-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="mobile",
            field=models.CharField(max_length=11),
        ),
    ]
