# Generated by Django 6.0.1 on 2026-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_booking_mobile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
    ]
