# Generated by Django 6.0.1 on 2026-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_booking_options_alter_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.CharField(max_length=10),
        ),
    ]
