# Generated by Django 6.0.1 on 2026-01-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_newsletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="subscribed_on",
            new_name="created_at",
        ),
    ]
